### ISSUE TITLE
Observable(this) in MyClass constructor vs Observable( MyClass.prototype )

### ISSUE THREAD

**Issue by erikhagreis** [florian/observable#3]
There seems to be a difference between following approaches:
```
var MyClass = function() {
   Observable(this)
};
```
and
```
var MyClass = function() {}

Observable(MyClass.prototype)
```

I would expect the same result functionally, but the latter approach behaves strangely to me. Two example implementations:

```
var handler = function() {
	console.log('handler triggered!');
};

var MyClass = function( ){
	Observable(this);
};

var one = new MyClass();
one.on('my_event', handler);
var two = new MyClass();
two.on('my_event', handler);

one.trigger('my_event'); // output: 1x 'handler triggered' log
```
Compare with:
```
var handler = function() {
   console.log('handler triggered!');
};

var MyClass = function( ){ };
Observable(MyClass.prototype);

var one = new MyClass();
one.on('my_event', handler);
var two = new MyClass();
two.on('my_event', handler);

one.trigger('my_event'); // output: 2x 'handler triggered' log
```

The behaviour of the second example surprised me. Is this intentional?

**Comment by florian** [comment]
I've just released v2 of the library which makes the extending clearer.
If you use ES6/CoffeeScript you can use `extends` to mixin all the functions, if not there's `Observable.mixin` which copies the needed methods. See the [README](https://github.com/florian/observable#usage) for more.
