### ISSUE TITLE
$ and jQuery

### ISSUE THREAD

**Issue by cope** [florian/observable#4]
This may be a stupid question, but is the $ object in the examples in conflict with jQuerys $ object?

In other words, can I use observable and jQuery together without issues?

Thanks.

**Comment by florian** [comment]
Maybe naming it `$` was indeed a bit confusing, I changed the README file to use the variable `x`.

To clarify: You have some object that you want to make observable. This object might be called `$` or `x`, it's really just your choice on how you name your variables and doesn't have anything to do with the library. I just needed some short variable name for the README file.
