### ISSUE TITLE
Only the result of the last .on(...) call can be unsubscribed with .off(...)

### ISSUE THREAD

**Issue by logi** [florian/observable#5]
From the documentation of .off(...): "This method accepts the return value of on / once and will unsubscribe all the subscribed functions." However, obj.on(...) simply return obj and obj.off(...) unsubscribes whatever was the last topic subscribed to.

Multiple subscriptions to the same topic can't be unsubscribed (as in the example below). Subscriptions to multiple topics on the same object can't be unsubcribed. This looks completely broken.

```javascript
// Running against version 1.2.1
var obj = {};
Observable(obj);

console.log('Subscribe twice to foo event');
var sB = obj.on('foo', function (n) { console.log('B: did foo', n); });
var sA = obj.on('foo', function (n) { console.log('A: did foo', n); });
console.log('sA === sB = ', sA === sB); // prints true
console.log('sA === obj = ', sA === obj); // prints true

obj.trigger('foo', [1]);  // Correctly prints 'A: did foo 1' and 'B: did foo 1'

console.log('Attempt to un-subscribe both');
obj.off(sB);
obj.off(sA); // Yeah, since sA === sB, this will do nothing
obj.trigger('foo', [2]);  // Prints 'B: did foo 2' but should print nothing.
```

**Comment by florian** [comment]
Yeah, the ID based system made the library too unpredictable. I've just released v2 which fixes this issue and makes the library nicer to use :)
